apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: web-deployment
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: nodevoto-frontend
      sync:
        infer:
          - '**/*.jsx'
          - '**/*.css'
          - '**/*.js'
          - '**/*.proto'
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
